// Predefined moments offered during onboarding and in Setup > Suggestions.
// `basic: true` ones are pre-selected during onboarding.
export const PRESETS = [
  { id: 'water', emoji: '💧', basic: true, importance: 2,
    name: { en: 'Drink water', fr: 'Boire de l’eau' },
    desc: { en: 'A full glass, right now.', fr: 'Un grand verre, tout de suite.' },
    slots: [['09:00', '10:00'], ['13:00', '14:00'], ['17:00', '18:00']] },
  { id: 'exercise', emoji: '🏃', basic: true, importance: 2,
    name: { en: 'Move your body', fr: 'Bouger' },
    desc: { en: '20 minutes is enough. Walk, stretch, anything.', fr: '20 minutes suffisent. Marche, étirements, n’importe quoi.' },
    slots: [['18:00', '19:30']] },
  { id: 'sleep', emoji: '😴', basic: true, importance: 3,
    name: { en: 'Go to bed', fr: 'Aller au lit' },
    desc: { en: 'Lights off. Tomorrow starts here.', fr: 'Lumières éteintes. Demain commence ici.' },
    slots: [['22:30', '23:15']] },
  { id: 'wake', emoji: '⏰', importance: 2,
    name: { en: 'Get up', fr: 'Se lever' },
    desc: { en: 'Feet on the floor, curtains open.', fr: 'Pieds au sol, rideaux ouverts.' },
    slots: [['07:00', '07:30']] },
  { id: 'meds', emoji: '💊', importance: 3,
    name: { en: 'Take medication', fr: 'Prendre ses médicaments' },
    desc: { en: '', fr: '' },
    slots: [['08:00', '09:00']] },
  { id: 'breakfast', emoji: '🥐', importance: 2,
    name: { en: 'Breakfast', fr: 'Petit-déjeuner' },
    desc: { en: 'Something real, not just coffee.', fr: 'Quelque chose de vrai, pas juste un café.' },
    slots: [['07:30', '08:30']] },
  { id: 'lunch', emoji: '🍽️', importance: 2,
    name: { en: 'Lunch', fr: 'Déjeuner' },
    desc: { en: 'Sit down. Eat. Screen away.', fr: 'Assieds-toi. Mange. Écran loin.' },
    slots: [['12:00', '13:30']] },
  { id: 'dinner', emoji: '🍲', importance: 2,
    name: { en: 'Dinner', fr: 'Dîner' },
    desc: { en: '', fr: '' },
    slots: [['19:00', '20:30']] },
  { id: 'shower', emoji: '🚿', importance: 1,
    name: { en: 'Shower', fr: 'Douche' },
    desc: { en: '', fr: '' },
    slots: [['07:15', '08:00']] },
  { id: 'teeth', emoji: '🪥', importance: 2,
    name: { en: 'Brush teeth', fr: 'Se brosser les dents' },
    desc: { en: 'Two minutes.', fr: 'Deux minutes.' },
    slots: [['08:00', '08:45'], ['22:00', '22:45']] },
  { id: 'air', emoji: '🌳', importance: 1,
    name: { en: 'Fresh air', fr: 'Prendre l’air' },
    desc: { en: 'Step outside for 10 minutes.', fr: 'Sors 10 minutes.' },
    slots: [['14:00', '16:00']] },
  { id: 'tidy', emoji: '🧹', importance: 1,
    name: { en: '10-minute tidy', fr: 'Rangement 10 min' },
    desc: { en: 'Timer on, one room, stop when it rings.', fr: 'Minuteur, une pièce, stop quand ça sonne.' },
    slots: [['20:00', '21:00']] },
  { id: 'plan', emoji: '📝', importance: 1,
    name: { en: 'Plan tomorrow', fr: 'Préparer demain' },
    desc: { en: 'Three things max.', fr: 'Trois choses maximum.' },
    slots: [['21:00', '21:30']] },
  { id: 'read', emoji: '📚', importance: 1,
    name: { en: 'Read', fr: 'Lire' },
    desc: { en: 'A few pages count.', fr: 'Quelques pages suffisent.' },
    slots: [['21:30', '22:30']] },
  { id: 'screens', emoji: '📵', importance: 2,
    name: { en: 'Screens off', fr: 'Écrans éteints' },
    desc: { en: 'Phone out of the bedroom.', fr: 'Téléphone hors de la chambre.' },
    slots: [['22:15', '22:45']] },
  { id: 'stretch', emoji: '🤸', importance: 1,
    name: { en: 'Stretch', fr: 'S’étirer' },
    desc: { en: '', fr: '' },
    slots: [['08:30', '09:00']] },
];
